name: Development
on:
  push:
    branches:
      - development
jobs:
  Plano:
    name: Plano do TF
    runs-on: ubuntu-latest
    environment: STG
    defaults:
      run:
        working-directory: ${{ github.workspace }}/deployment/terraform
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
          terraform_wrapper: false
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: terraform init
        id: init
        run: terraform init
      - name: terraform workspace
        run: terraform workspace select stg
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: terraform plan
        id: plan
        run: terraform plan -var-file=environments/stg.tfvars -out=tfplan.json -no-color
        continue-on-error: true
