name: Apply Staging
on:
  push:
    branches:
      - staging
jobs:
  Deploy:
    name: Deploy para staging
    runs-on: ubuntu-latest
    environment: STG
    defaults:
      run:
        working-directory: ${{ github.workspace }}/deployment/terraform
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
          terraform_wrapper: false
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: terraform init
        run: terraform init
      - name: terraform workspace
        run: terraform workspace select stg
      - name: terraform plan
        run: terraform plan -var-file=environments/stg.tfvars -out=tfplan.json -no-color
      - name: terraform apply
        run: terraform apply -auto-approve tfplan.json
